// ─── Rental List Columns Catalog ─────────────────────────────
// source_field → column definition for rental vehicles list view

export const RENTAL_COLUMNS_CATALOG = {
  vehicle_id:    { label: 'Vehicle ID',     defaultWidth: '90px'  },
  brand_model:   { label: 'Brand / Model',  defaultWidth: '130px' },
  plate:         { label: 'Plate',          defaultWidth: '100px' },
  type:          { label: 'Type',           defaultWidth: '80px'  },
  class:         { label: 'Class',          defaultWidth: '90px'  },
  driver:        { label: 'Driver',         defaultWidth: '130px' },
  second_driver: { label: '2nd Driver',     defaultWidth: '130px' },
  dept:          { label: 'Dept',           defaultWidth: '100px' },
  start:         { label: 'Start',          defaultWidth: '90px'  },
  end:           { label: 'End',            defaultWidth: '90px'  },
  days:          { label: 'Days',           defaultWidth: '60px'  },
  billing_unit:  { label: 'Billing',        defaultWidth: '70px'  },
  rate:          { label: 'Rate',           defaultWidth: '80px'  },
  total_no_vat:  { label: 'No VAT',         defaultWidth: '90px'  },
  total_vat:     { label: '+ VAT',          defaultWidth: '90px'  },
  currency:      { label: 'Currency',       defaultWidth: '70px'  },
  status:        { label: 'Status',         defaultWidth: '80px'  },
  voucher:       { label: 'Voucher',        defaultWidth: '120px' },
  po:            { label: 'P.O.',           defaultWidth: '80px'  },
  contract_no:   { label: 'Contract',       defaultWidth: '100px' },
  insurance:     { label: 'Insurance',      defaultWidth: '100px' },
  km:            { label: 'KM',             defaultWidth: '90px'  },
  notes:         { label: 'Notes',          defaultWidth: '140px' },
}

export const RENTAL_DEFAULT_PRESET = [
  { source_field: 'vehicle_id',    header_label: 'Vehicle ID',    width: '90px',  display_order: 1  },
  { source_field: 'brand_model',   header_label: 'Brand / Model', width: '130px', display_order: 2  },
  { source_field: 'plate',         header_label: 'Plate',         width: '100px', display_order: 3  },
  { source_field: 'type',          header_label: 'Type',          width: '80px',  display_order: 4  },
  { source_field: 'class',         header_label: 'Class',         width: '90px',  display_order: 5  },
  { source_field: 'driver',        header_label: 'Driver',        width: '130px', display_order: 6  },
  { source_field: 'second_driver', header_label: '2nd Driver',    width: '130px', display_order: 7  },
  { source_field: 'dept',          header_label: 'Dept',          width: '100px', display_order: 8  },
  { source_field: 'start',         header_label: 'Start',         width: '90px',  display_order: 9  },
  { source_field: 'end',           header_label: 'End',           width: '90px',  display_order: 10 },
  { source_field: 'days',          header_label: 'Days',          width: '60px',  display_order: 11 },
  { source_field: 'rate',          header_label: 'Rate',          width: '80px',  display_order: 12 },
  { source_field: 'total_no_vat',  header_label: 'No VAT',        width: '90px',  display_order: 13 },
  { source_field: 'total_vat',     header_label: '+ VAT',         width: '90px',  display_order: 14 },
  { source_field: 'status',        header_label: 'Status',        width: '80px',  display_order: 15 },
  { source_field: 'voucher',       header_label: 'Voucher',       width: '120px', display_order: 16 },
  { source_field: 'po',            header_label: 'P.O.',          width: '80px',  display_order: 17 },
  { source_field: 'notes',         header_label: 'Notes',         width: '140px', display_order: 18 },
]
