-- S22 follow-up (aggiornato): normalizza department in crew — UPPERCASE + DEPT_MAP completo
-- Eseguire in Supabase SQL Editor

-- STEP 1: uppercase + trim tutto
UPDATE crew
SET department = UPPER(TRIM(department))
WHERE department IS NOT NULL;

-- STEP 2: applica DEPT_MAP — ogni gruppo mappa forme alternate al valore canonico

-- CAMERA
UPDATE crew SET department = 'CAMERA'
WHERE department IN ('CAMERAS','CAMERA DEPARTMENT','CAMERA DEPT','CAMERA DEPT.','CAMERA/VIDEO','VIDEO','DIT','CAMERA UNIT','FOTOGRAFIA','MACCHINA','RIPRESE','OPERATORI');

-- GRIP
UPDATE crew SET department = 'GRIP'
WHERE department IN ('GRIPS','GRIP DEPARTMENT','GRIP DEPT','KEY GRIP','MACCHINISTI');

-- ELECTRIC
UPDATE crew SET department = 'ELECTRIC'
WHERE department IN ('ELECTRICS','ELECTRICAL','ELECTRICALS','ELECTRIC DEPARTMENT','ELECTRIC DEPT','LIGHTING','LIGHTS','GAFFERS','GAFFER','ELETTRICISTI','LUCI','ILLUMINAZIONE');

-- SOUND
UPDATE crew SET department = 'SOUND'
WHERE department IN ('AUDIO','SOUND DEPARTMENT','SOUND DEPT','SOUNDS','SUONO','FONICO');

-- ART
UPDATE crew SET department = 'ART'
WHERE department IN ('ART DEPARTMENT','ART DEPT','ART DEPT.','PRODUCTION DESIGN','PRODUCTION DESIGNER','CONSTRUCTION','SCENOGRAFIA','REPARTO ARTE');

-- COSTUME
UPDATE crew SET department = 'COSTUME'
WHERE department IN ('COSTUMES','COSTUME DEPARTMENT','COSTUME DEPT','WARDROBE','WARDROBE DEPARTMENT','WARDROBE DEPT','COSTUMI','SARTORIA');

-- MAKEUP
UPDATE crew SET department = 'MAKEUP'
WHERE department IN ('MAKE UP','MAKE-UP','MAKEUP DEPARTMENT','MAKEUP DEPT','MAKE UP DEPARTMENT','MAKE UP DEPT','TRUCCO');

-- HMU
UPDATE crew SET department = 'HMU'
WHERE department IN ('HAIR & MAKE UP','HAIR AND MAKE UP','HAIR AND MAKEUP','HAIR & MAKEUP','HAIR & MAKE-UP','HAIR AND MAKE-UP','H&MU','HAIR/MAKEUP','HAIR/MAKE UP','HAIR & MU','HAIR','PARRUCCHIERI','TRUCCO E PARRUCCHIERI','TRUCCO & PARRUCCHIERI','TRUCCO/PARRUCCHIERI','ACCONCIATURE');

-- PRODUCTION
UPDATE crew SET department = 'PRODUCTION'
WHERE department IN ('PRODUCTION DEPARTMENT','PRODUCTION DEPT','PROD','PRODUCTION OFFICE','LINE PRODUCTION','PRODUZIONE','SEGRETERIA DI PRODUZIONE','SEGRETERIA DI EDIZIONE');

-- TRANSPORT
UPDATE crew SET department = 'TRANSPORT'
WHERE department IN ('TRANSPORTATION','TRANSPORTS','TRANSPORT DEPARTMENT','TRANSPORT DEPT','DRIVERS','DRIVING','DRIVER','TRASPORTI','AUTISTI','TRASPORTATORI');

-- AD
UPDATE crew SET department = 'AD'
WHERE department IN ('ASSISTANT DIRECTORS','ASSISTANT DIRECTOR','ADS','1ST AD','2ND AD','3RD AD','FLOOR','AIUTO REGIA','AIUTO REGISTA','ASSISTENTI ALLA REGIA');

-- PROPS
UPDATE crew SET department = 'PROPS'
WHERE department IN ('PROPERTY','PROPERTIES','PROP','PROPS DEPARTMENT','PROPS DEPT','PROP DEPT','OGGETTI DI SCENA','ACCESSORISTICA','ATTREZZERIA');

-- SET DEC
UPDATE crew SET department = 'SET DEC'
WHERE department IN ('SET DEC & SET DRESSING','SET DEC AND SET DRESSING','SET DECORATION','SET DRESSING','SET DECOR','SET DÉCOR','SET DECORATION DEPARTMENT','ARREDAMENTO','ARREDAMENTO DI SCENA','DECORAZIONE SET');

-- ACCOUNTING
UPDATE crew SET department = 'ACCOUNTING'
WHERE department IN ('ACCOUNTS','FINANCE','PAYROLL','ACCOUNTING DEPARTMENT','ACCOUNTANTS','ACCOUNTS DEPARTMENT','FINANCE DEPARTMENT','AMMINISTRAZIONE','CONTABILITÀ','CONTABILITA');

-- PRODUCERS
UPDATE crew SET department = 'PRODUCERS'
WHERE department IN ('WRITER','WRITERS','WRITING','WRITERS / DIRECTORS','PRODUCERS / WRITERS / DIRECTORS','PRODUCERS/WRITERS/DIRECTORS','EXECUTIVE PRODUCERS','DEVELOPMENT','STORY','PRODUTTORI','SVILUPPO');

-- CATERING
UPDATE crew SET department = 'CATERING'
WHERE department IN ('CRAFT SERVICE','CRAFT SERVICES','CRAFTY','CATERING DEPARTMENT','CATERING SERVICE','KITCHEN','MENSA','VETTOVAGLIAMENTO');

-- SECURITY
UPDATE crew SET department = 'SECURITY'
WHERE department IN ('SECURITY DEPARTMENT','GUARDS','SECURITY PERSONNEL','SECURITY GUARD','SICUREZZA','VIGILANZA');

-- MEDICAL
UPDATE crew SET department = 'MEDICAL'
WHERE department IN ('MEDIC','SET MEDIC','HEALTH AND SAFETY','HEALTH & SAFETY','H&S','FIRST AID','NURSE','PARAMEDIC','MEDICI','ASSISTENZA MEDICA','SALUTE E SICUREZZA');

-- VFX
UPDATE crew SET department = 'VFX'
WHERE department IN ('VISUAL EFFECTS','VISUAL EFFECTS DEPARTMENT','VFX DEPARTMENT','SPECIAL EFFECTS','SFX','POST PRODUCTION','POST-PRODUCTION','EFFETTI SPECIALI','EFFETTI VISIVI','POST PRODUZIONE');

-- DIRECTING
UPDATE crew SET department = 'DIRECTING'
WHERE department IN ('DIRECTORS','DIRECTOR','DIRECTION','DIRECTING DEPARTMENT','REGIA');

-- CAST
UPDATE crew SET department = 'CAST'
WHERE department IN ('ACTORS','ACTOR','TALENT','PRINCIPAL CAST','BACKGROUND','EXTRAS','SUPPORTING ARTISTS','SA','BACKGROUND ARTISTS','ATTORI','CAST ARTISTICO','COMPARSE');

-- LOCATIONS
UPDATE crew SET department = 'LOCATIONS'
WHERE department IN ('LOCATION','LOCATION DEPARTMENT','LOCATIONS DEPARTMENT','LOCATIONS DEPT','LOCATION DEPT','SCOUTS','LOCATION MANAGERS','SOPRALLUOGHI');

-- OTHER
UPDATE crew SET department = 'OTHER'
WHERE department IN ('MISC','MISCELLANEOUS','GENERAL','TBC','N/A','STUNT','STUNTS','STUNT DEPARTMENT','VARI','ALTRO');
